# MiMo Startup Diagnostic Runner
# Launches ONE MiMo version, collects full startup telemetry,
# and waits for the user to manually close it. No auto-kill.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File bench-run.ps1 -Side ARM64
#   powershell -ExecutionPolicy Bypass -File bench-run.ps1 -Side x64
#
# Output: bench-output\<Side>-<timestamp>\
#   - stderr.log          (Electron stderr / --enable-logging)
#   - app-log-snapshot\   (copy of %APPDATA%\Xiaomi MiMo\logs)
#   - milestones.txt      (detected startup milestones with timestamps)
#   - process-stats.csv   (RSS / handle count sampled every 2s)
#   - canvas-binding-error.log (if generated by our diagnostic patch)

param(
    [Parameter(Mandatory=$true)]
    [ValidateSet("ARM64", "x64")]
    [string]$Side,

    [int]$SampleIntervalMs = 2000
)

$ErrorActionPreference = "Stop"

# --- Paths ---
$arm64Exe = "C:\Users\xiaomi\XiaomiMiMoProjects\electron-arm64-port\output\Xiaomi MiMo ARM64\Xiaomi MiMo.exe"
$x64Exe   = "C:\Users\xiaomi\AppData\Local\Programs\Xiaomi MiMo\Xiaomi MiMo.exe"
$realUd   = Join-Path $env:APPDATA "Xiaomi MiMo"
$appLogDir = Join-Path $realUd "logs"
$outRoot  = "C:\Users\xiaomi\XiaomiMiMoProjects\electron-arm64-port\scripts\bench-output"

$exePath = if ($Side -eq "ARM64") { $arm64Exe } else { $x64Exe }
$exeDir  = Split-Path $exePath -Parent
$stamp   = Get-Date -Format "yyyyMMdd-HHmmss"
$outDir  = Join-Path $outRoot "$Side-$stamp"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null

Write-Host "MiMo Startup Diagnostic Runner" -ForegroundColor Yellow
Write-Host "  Side     : $Side"
Write-Host "  Exe      : $exePath"
Write-Host "  Output   : $outDir"
Write-Host ""

# --- Preflight ---
$running = Get-Process -Name "Xiaomi MiMo" -ErrorAction SilentlyContinue
if ($running) {
    Write-Host "WARNING: Xiaomi MiMo is already running ($($running.Count) processes)." -ForegroundColor Red
    Write-Host "Close ALL instances first, or the new instance may hit single-instance lock."
    Write-Host "Press Enter to continue anyway, or Ctrl+C to abort..."
    Read-Host | Out-Null
}

# Snapshot app log dir state before launch
$logFilesBefore = @()
if (Test-Path $appLogDir) {
    $logFilesBefore = @(Get-ChildItem $appLogDir -Filter "*.log" -ErrorAction SilentlyContinue)
}

# --- Launch ---
$psi = New-Object System.Diagnostics.ProcessStartInfo
$psi.FileName = $exePath
$psi.WorkingDirectory = $exeDir
$psi.Arguments = "--enable-logging=stderr"
$psi.UseShellExecute = $false
$psi.RedirectStandardError = $true
$psi.RedirectStandardOutput = $true
$psi.StandardErrorEncoding = [System.Text.Encoding]::UTF8
$psi.StandardOutputEncoding = [System.Text.Encoding]::UTF8

# Per-process env: ARM64 gets the native lib path for canvas binding
if ($Side -eq "ARM64") {
    $nativeLib = Join-Path $exeDir "resources\native\skia.win32-arm64-msvc.node"
    if (Test-Path $nativeLib) {
        $psi.EnvironmentVariables["NAPI_RS_NATIVE_LIBRARY_PATH"] = $nativeLib
        Write-Host "  NAPI_RS_NATIVE_LIBRARY_PATH = $nativeLib"
    }
}

$stderrFile = Join-Path $outDir "stderr.log"
$stdoutFile = Join-Path $outDir "stdout.log"
$milestoneFile = Join-Path $outDir "milestones.txt"
$statsFile = Join-Path $outDir "process-stats.csv"

$sw = [System.Diagnostics.Stopwatch]::StartNew()

Write-Host "Launching... (close MiMo manually when done)" -ForegroundColor Cyan
$proc = [System.Diagnostics.Process]::Start($psi)

# --- Async stderr capture to file ---
$stderrWriter = [System.IO.StreamWriter]::new($stderrFile, $false, [System.Text.Encoding]::UTF8)
$stdoutWriter = [System.IO.StreamWriter]::new($stdoutFile, $false, [System.Text.Encoding]::UTF8)
$mileWriter   = [System.IO.StreamWriter]::new($milestoneFile, $false, [System.Text.Encoding]::UTF8)
$statsWriter  = [System.IO.StreamWriter]::new($statsFile, $false, [System.Text.Encoding]::UTF8)
$statsWriter.WriteLine("TimestampMs,RSS_MB,HandleCount,CPU_s,ProcCount")

$milestones = [ordered]@{}
$stderrTask = $proc.StandardError.ReadLineAsync()
$stdoutTask = $proc.StandardOutput.ReadLineAsync()

function Write-Milestone {
    param([string]$Name, [string]$Detail = "")
    $ts = $sw.ElapsedMilliseconds
    $line = "[${ts}ms] $Name $(if($Detail){"$Detail"})"
    $script:mileWriter.WriteLine($line)
    $script:mileWriter.Flush()
    Write-Host "  [+] $line" -ForegroundColor Green
    $script:milestones[$Name] = $ts
}

function Write-Stats {
    $procs = Get-Process -Name "Xiaomi MiMo" -ErrorAction SilentlyContinue |
        Where-Object { $_.Path -like "$script:exeDir*" }
    if (-not $procs) { return }
    $rss = [math]::Round((($procs | Measure-Object WorkingSet64 -Sum).Sum / 1MB), 1)
    $handles = ($procs | Measure-Object HandleCount -Sum).Sum
    $cpu = [math]::Round((($procs | Measure-Object CPU -Sum).Sum), 1)
    $ts = $sw.ElapsedMilliseconds
    $script:statsWriter.WriteLine("$ts,$rss,$handles,$cpu,$($procs.Count)")
    $script:statsWriter.Flush()
}

# --- Main collection loop ---
Write-Host ""
Write-Host "Collecting... (process will run until you close it)" -ForegroundColor Yellow
Write-Host "  stderr -> $stderrFile"
Write-Host "  stats  -> $statsFile"
Write-Host ""

$lastStatMs = 0
$uiPainted = $false

while (-not $proc.HasExited) {
    Start-Sleep -Milliseconds 200

    # Drain stderr
    while ($stderrTask.IsCompleted -and $stderrTask.Result -ne $null) {
        $line = $stderrTask.Result
        $ts = $sw.ElapsedMilliseconds
        $stderrWriter.WriteLine("[$ts] $line")
        $stderrWriter.Flush()

        # Detect milestones from stderr
        if ($line -match 'INFO:CONSOLE' -and -not $milestones['landing-page']) {
            Write-Milestone "landing-page" "first INFO:CONSOLE (React bundle executed)"
        }
        if ($line -match 'loadEngineSessions.*total\s*=\s*(\d+)' -and -not $milestones['projects-loaded']) {
            $ms = $matches[1]
            Write-Milestone "projects-loaded" "loadEngineSessions total=${ms}ms"
        }
        if ($line -match 'engine in-process server ready' -and -not $milestones['engine-ready']) {
            Write-Milestone "engine-ready" $line.Trim()
        }
        if ($line -match 'automation background startup settled' -and -not $milestones['startup-settled']) {
            Write-Milestone "startup-settled" $line.Trim()
        }

        $stderrTask = $proc.StandardError.ReadLineAsync()
    }

    # Drain stdout
    while ($stdoutTask.IsCompleted -and $stdoutTask.Result -ne $null) {
        $line = $stdoutTask.Result
        $ts = $sw.ElapsedMilliseconds
        $stdoutWriter.WriteLine("[$ts] $line")
        $stdoutWriter.Flush()
        $stdoutTask = $proc.StandardOutput.ReadLineAsync()
    }

    # Milestone 1: Window appears
    try {
        $proc.Refresh()
        if (-not $milestones['window-title'] -and $proc.MainWindowTitle -eq "Xiaomi MiMo") {
            Write-Milestone "window-title" "MainWindowTitle = 'Xiaomi MiMo'"
        }
    } catch {}

    # Milestone 2: Shimmer logo painted (startup-loader in HTML, visible on first paint)
    if ($milestones['window-title'] -and -not $milestones['shimmer-painted']) {
        try {
            $proc.Refresh()
            $rect = $proc.MainWindowRectangle
            if ($rect.Width -gt 0 -and $rect.Height -gt 0) {
                Write-Milestone "shimmer-painted" "window $($rect.Width)x$($rect.Height) (startup-loader first paint)"
            }
        } catch {}
        # Fallback: force after 200ms past window-title
        if (-not $milestones['shimmer-painted'] -and ($sw.ElapsedMilliseconds - $milestones['window-title']) -gt 200) {
            Write-Milestone "shimmer-painted" "fallback +200ms after window-title"
        }
    }

    # Periodic stats
    $now = $sw.ElapsedMilliseconds
    if ($now - $lastStatMs -ge $SampleIntervalMs) {
        Write-Stats
        $lastStatMs = $now
    }

}

$sw.Stop()

# --- Post-exit: collect everything ---
Write-Host ""
Write-Host "Process exited (code $($proc.ExitCode))" -ForegroundColor Yellow

# Final stats
Write-Stats

# Close writers
$stderrWriter.Close()
$stdoutWriter.Close()
$statsWriter.Close()
$mileWriter.Close()

# Wait a moment for log file flush
Start-Sleep -Seconds 2

# Snapshot app logs
$appLogSnap = Join-Path $outDir "app-log-snapshot"
New-Item -ItemType Directory -Force -Path $appLogSnap | Out-Null
if (Test-Path $appLogDir) {
    $logFilesAfter = @(Get-ChildItem $appLogDir -Filter "*.log" -ErrorAction SilentlyContinue)
    foreach ($f in $logFilesAfter) {
        Copy-Item $f.FullName $appLogSnap -Force
    }
    # Also copy any new log files that appeared
    $newLogs = $logFilesAfter | Where-Object { $_.Name -notin ($logFilesBefore | ForEach-Object { $_.Name }) }
    foreach ($f in $newLogs) {
        Copy-Item $f.FullName $appLogSnap -Force
    }
}

# Copy canvas diagnostic log if it exists
$canvasLog = Join-Path $exeDir "canvas-binding-error.log"
if (Test-Path $canvasLog) {
    Copy-Item $canvasLog $outDir -Force
}

# Copy Code Cache state note
$codeCache = Join-Path $realUd "Code Cache"
$ccSize = if (Test-Path $codeCache) {
    [math]::Round(((Get-ChildItem $codeCache -Recurse -File | Measure-Object Length -Sum).Sum / 1MB), 1)
} else { 0 }

# --- Summary ---
$summaryFile = Join-Path $outDir "summary.txt"
$summary = @"
MiMo Startup Diagnostic - $Side
================================
Timestamp   : $stamp
Exe         : $exePath
Exit code   : $($proc.ExitCode)
Total time  : $($sw.ElapsedMilliseconds) ms
Code Cache  : $ccSize MB at exit

Milestones:
"@
foreach ($k in $milestones.Keys) {
    if ($k -like '_*') { continue }
    $summary += "  $($k) : $($milestones[$k]) ms`n"
}
$summary += "`nOutput files:`n  stderr.log`n  stdout.log`n  process-stats.csv`n  milestones.txt`n  app-log-snapshot\`n"

Set-Content -Path $summaryFile -Value $summary -Encoding UTF8

Write-Host ""
Write-Host "========================================" -ForegroundColor Yellow
Write-Host "  RESULTS saved to: $outDir" -ForegroundColor Yellow
Write-Host "========================================" -ForegroundColor Yellow
Write-Host ""
Write-Host $summary

# Clean up any remaining child processes
$remaining = Get-Process -Name "Xiaomi MiMo" -ErrorAction SilentlyContinue |
    Where-Object { $_.Path -like "$exeDir*" }
if ($remaining) {
    Write-Host "Cleaning up $($remaining.Count) remaining processes..." -ForegroundColor Yellow
    foreach ($p in $remaining) {
        Stop-Process -Id $p.Id -Force -ErrorAction SilentlyContinue
    }
}
